custom.cloudbuildDisableWorkerPoolExternalIP:
  actionType: DENY
  condition: (resource.privatePoolV1Config.networkConfig.egressOption != "NO_PUBLIC_EGRESS")
  description: Ensure no unauthorized worker pools external ip used for each build
  displayName: Deny unauthorized worker pools external ip used for each build
  methodTypes:
  - CREATE
  - UPDATE
  resourceTypes:
  - cloudbuild.googleapis.com/WorkerPool
