# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  _DOCKER_REGION: us-central1
  _PROJECT_ID: risk-analysis-asset
  _BACKEND_IMAGE_NAME: risk-analysis-backend
  _FRONTEND_IMAGE_NAME: risk-analysis-frontend
  _BACKEND_SERVICE_NAME: risk-analysis-backend-v3
  _FRONTEND_SERVICE_NAME: risk-analysis-frontend-v3
  _IMAGE_TAG: v9  
  # _MODIFIED_SERVICE: "both" # Or "backend" or "frontend"
  # _DEPLOY_UPDATE: "false"

steps:
#Build and Push Backend Service Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_BACKEND_IMAGE_NAME}', './backend' ]
  #if: '${_MODIFIED_SERVICE == "backend" || $_MODIFIED_SERVICE == "both"}'
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_BACKEND_IMAGE_NAME}:latest', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_BACKEND_IMAGE_NAME}:${_IMAGE_TAG}']
  #if: $_MODIFIED_SERVICE == "backend" || $_MODIFIED_SERVICE == "both"
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_BACKEND_IMAGE_NAME}:${_IMAGE_TAG}']
  #if: $_MODIFIED_SERVICE == "backend" || $_MODIFIED_SERVICE == "both"

#Build and Push Frontend Service Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_FRONTEND_IMAGE_NAME}', './frontend' ]
  #if: $_MODIFIED_SERVICE == "frontend" || $_MODIFIED_SERVICE == "both"
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_FRONTEND_IMAGE_NAME}:latest', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_FRONTEND_IMAGE_NAME}:${_IMAGE_TAG}']
 #if: $_MODIFIED_SERVICE == "frontend" || $_MODIFIED_SERVICE == "both"
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_FRONTEND_IMAGE_NAME}:${_IMAGE_TAG}']
 #if: $_MODIFIED_SERVICE == "frontend" || $_MODIFIED_SERVICE == "both"

#Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '${_BACKEND_SERVICE_NAME}', '--image', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_BACKEND_IMAGE_NAME}:${_IMAGE_TAG}', '--region', '${_DOCKER_REGION}']
  #if: ($_MODIFIED_SERVICE == "backend" || $_MODIFIED_SERVICE == "both") && $_DEPLOY_UPDATE == "true"
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '${_FRONTEND_SERVICE_NAME}', '--image', '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_FRONTEND_IMAGE_NAME}:${_IMAGE_TAG}', '--region', '${_DOCKER_REGION}']
 # if: ($_MODIFIED_SERVICE == "frontend" || $_MODIFIED_SERVICE == "both") && $_DEPLOY_UPDATE == "true"

images:
  - '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_BACKEND_IMAGE_NAME}'
  - '${_DOCKER_REGION}-docker.pkg.dev/${_PROJECT_ID}/risk-analysis/${_FRONTEND_IMAGE_NAME}'